import React from "react"
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Inter_Tight, JetBrains_Mono } from 'next/font/google'
import { Analytics } from '@vercel/analytics/next'
import { ThemeProvider } from '@/components/theme-provider'
import { GlobalThemeToggle } from '@/components/brand/global-theme-toggle'
import { AuthProvider } from '@/lib/auth-context'
import { Toaster } from '@/components/ui/sonner'
import './globals.css'

const geist = localFont({
  src: [
    { path: '../node_modules/geist/dist/fonts/geist-sans/Geist-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../node_modules/geist/dist/fonts/geist-sans/Geist-Medium.woff2', weight: '500', style: 'normal' },
    { path: '../node_modules/geist/dist/fonts/geist-sans/Geist-SemiBold.woff2', weight: '600', style: 'normal' },
    { path: '../node_modules/geist/dist/fonts/geist-sans/Geist-Bold.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-geist'
})

const geistMono = localFont({
  src: [
    { path: '../node_modules/geist/dist/fonts/geist-mono/GeistMono-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../node_modules/geist/dist/fonts/geist-mono/GeistMono-Medium.woff2', weight: '500', style: 'normal' },
    { path: '../node_modules/geist/dist/fonts/geist-mono/GeistMono-SemiBold.woff2', weight: '600', style: 'normal' },
    { path: '../node_modules/geist/dist/fonts/geist-mono/GeistMono-Bold.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-geist-mono'
})

const interTight = Inter_Tight({
  subsets: ["latin"],
  variable: '--font-inter-tight'
})

const jetbrainsMono = JetBrains_Mono({ 
  subsets: ["latin"],
  variable: '--font-jetbrains'
});

export const metadata: Metadata = {
  title: 'Formix — Forms as Code',
  description: 'Define forms in a custom DSL, version-control them in Git, and render live interactive UIs with an AI generation layer. No drag-and-drop. No JSON configs.',
  icons: {
    // Theme-aware favicon: the browser picks light/dark by prefers-color-scheme.
    // The plain formix.svg entry is the fallback for browsers that ignore the
    // media attribute. apple-icon.png is the iOS home-screen touch icon (full
    // square — Apple applies its own mask). All generated by scripts/rasterize-mark.mjs.
    icon: [
      { url: '/formix.svg', type: 'image/svg+xml' },
      { url: '/icon-light.png', sizes: '32x32', type: 'image/png', media: '(prefers-color-scheme: light)' },
      { url: '/icon-dark.png', sizes: '32x32', type: 'image/png', media: '(prefers-color-scheme: dark)' },
    ],
    apple: [{ url: '/apple-icon.png', sizes: '180x180', type: 'image/png' }],
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geist.variable} ${geistMono.variable} ${interTight.variable} ${jetbrainsMono.variable} font-sans antialiased`}>
        {/* One continuous background hue wash behind every page (design.md
            §Color System) — fixed, top-left origin, low chroma. This is
            what glass panels blur against; without it nothing reads as
            glass. Single instance, never per-section. */}
        <div className="bg-hue-wash" aria-hidden="true" />
        <ThemeProvider attribute="class" defaultTheme="light" disableTransitionOnChange>
          <AuthProvider>
            {children}
            <GlobalThemeToggle />
            <Toaster />
          </AuthProvider>
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  )
}
