"""add duplicate_mode, submission metadata, form_views

Revision ID: e924d259facc
Revises: 
Create Date: 2026-07-29 17:58:55.340179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e924d259facc'
down_revision: Union[str, Sequence[str], None] = "0001_initial_schema"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_views',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('form_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_id', 'session_id', name='uq_form_views_form_session')
    )
    with op.batch_alter_table('form_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_views_form_id'), ['form_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_views_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('forms', schema=None) as batch_op:
        # server_default backfills existing rows; dropped right after so the
        # column's default going forward is purely the Python-side model default.
        batch_op.add_column(sa.Column('duplicate_mode', sa.String(), nullable=False, server_default='multiple'))
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.alter_column('duplicate_mode', server_default=None)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('browser', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('device', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('started_at')
        batch_op.drop_column('device')
        batch_op.drop_column('browser')
        batch_op.drop_column('user_agent')

    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_column('duplicate_mode')

    with op.batch_alter_table('form_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_views_session_id'))
        batch_op.drop_index(batch_op.f('ix_form_views_form_id'))

    op.drop_table('form_views')
    # ### end Alembic commands ###
